export interface BusinessSettings {
  id: 'business-settings'
  businessName: string
  phone: string
  email: string
  website: string
  streetAddress: string
  city: string
  state: string
  zipCode: string
  defaultTaxRate: number
  defaultTaxReservePercent: number
  defaultLaborRate: number
  minimumJobCharge: number
  serviceCallCharge: number
  diagnosticFee: number
  travelCharge: number
  afterHoursRatePercent: number
  weekendRatePercent: number
  emergencyRatePercent: number
  defaultMaterialMarkupPercent: number
  defaultOverheadPercent: number
  targetGrossMarginPercent: number
  defaultDeliveryCost: number
  defaultDisposalCost: number
  darkMode: boolean
  estimateValidDays: number
  invoiceDueDays: number
  estimatePrefix: string
  invoicePrefix: string
  estimateTerms: string
  invoiceTerms: string
  emailNotifications: boolean
  leadNotifications: boolean
  updatedAt: string
}
